spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  datasource:
    url: jdbc:mysql://database-1.cty5w37htsqx.ap-northeast-2.rds.amazonaws.com:3306/wedding_invitation_DB?serverTimezone=Asia/Seoul
    username: ryouzhe
    password: tjwlgns0-=
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
